name: Web API to DockerHub to Azure

on:
  push:
    branches:
        - 'main'
        - 'dev'
    paths:
        - './FireLibrary2/'
  pull_request:
    branches: 
        - 'main'
        - 'dev'
  workflow_dispatch:
jobs:

  build_docker_image:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Build the Docker image
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./FireLibrary2/
          file: ./FireLibrary2/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/firelibrary2:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/firelibrary2:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/firelibrary2:buildcache,mode=max
          
