# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - firelibrarydocker

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_98e534c1fb1e405f9a7e9034c6a36920 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_676837f4d5a64392a5fdda2fd1eaf1e5 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_98e534c1fb1e405f9a7e9034c6a36920 }}/jdelacruz087/firelibrary:${{ github.sha }}
          file: ./FireLibrary2/Dockerfile

  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'firelibrarydocker'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_2edf3c63dd4949b684b6594cfa0beea5 }}
            images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_98e534c1fb1e405f9a7e9034c6a36920 }}/jdelacruz087/firelibrary:${{ github.sha }}'
