name: angular-dockerhub
on:
  push:
    branches:
      - main
      - dev
    paths:
      - './fire-library-spa/'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./fire-library-spa/package-lock.json
    - run: npm --prefix ./fire-library-spa/ ci
    - run: npm --prefix ./fire-library-spa/ run build --if-present
    # - run: npm --prefix ./client/ test
  
  docker:
      needs: build
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout 
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./fire-library-spa/
            file: ./fire-library-spa/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/firelibraryspa:latest
